---
title: "IPEDS Data"
author: "Himanshi Manglunia, Kalpita Raut, Laura Walker"
date: "November 19, 2018"
output: html_document
---

```{r setup, include=FALSE}
# Load RODBC package 
# Connects R Code to the database/warehouse
# install.packages("RODBC") # only needs to be run once
library(RODBC)
library(reshape2)

#Be sure to go to this site and download all the data. Save excel files locally. (will need to convert from csv to xlsx https://collegescorecard.ed.gov/data/ 

```
 ## Data from year 2015-16
```{r message=FALSE, cache=FALSE, echo=FALSE, warning=FALSE}

bigten <- data.frame(UNITID=c(151351, 171100, 147767, 204796, 214777, 243780, 186380, 145637, 153658, 163286, 170976, 174066, 181464, 240444), name=c('Indiana University', 'Michigan State University', 'Northwestern University', 'The Ohio State University', 'Penn State University', 'Purdue University', 'Rutgers University', 'University of Illinois at Urbana-Champaign', 'University of Iowa', 'University of Maryland', 'University of Michigan - Ann Arbor', 'University of Minnesota', 'University of Nebraska', 'University of Wisconsin'))
```


```{r message=FALSE, cache=FALSE, echo=FALSE, warning=FALSE}
library(readxl)
MERGED2016_17_PP <- read_excel("MERGED2016_17_PP.xlsx")
MERGED2016_17_PP <- merge(bigten, MERGED2016_17_PP, by.x="UNITID", by.y="UNITID", all.x = TRUE)
MERGED2016_17_PP$Year <- "2016-17"

MERGED2016_17_PP <- MERGED2016_17_PP[,c("PCIP01", "PCIP03", "PCIP04", "PCIP05", "PCIP09", "PCIP10", "PCIP11", "PCIP12", "PCIP13", "PCIP14", "PCIP15", "PCIP16", "PCIP19", "PCIP22", "PCIP23", "PCIP24", "PCIP25", "PCIP26", "PCIP27", "PCIP29", "PCIP30", "PCIP31", "PCIP38", "PCIP39", "PCIP40", "PCIP41", "PCIP42", "PCIP43", "PCIP44", "PCIP45", "PCIP46", "PCIP47", "PCIP48", "PCIP49", "PCIP50", "PCIP51", "PCIP52", "PCIP54", "CIP01BACHL", "CIP03BACHL", "CIP04BACHL", "CIP05BACHL", "CIP09BACHL", "CIP10BACHL", "CIP11BACHL", "CIP12BACHL", "CIP13BACHL", "CIP14BACHL", "CIP15BACHL", "CIP16BACHL", "CIP19BACHL", "CIP22BACHL", "CIP23BACHL", "CIP24BACHL", "CIP25BACHL", "CIP26BACHL", "CIP27BACHL", "CIP29BACHL", "CIP30BACHL", "CIP31BACHL", "CIP38BACHL", "CIP39BACHL", "CIP40BACHL", "CIP41BACHL", "CIP42BACHL", "CIP43BACHL", "CIP44BACHL", "CIP45BACHL", "CIP46BACHL", "CIP47BACHL", "CIP48BACHL", "CIP49BACHL", "CIP50BACHL", "CIP51BACHL", "CIP52BACHL", "CIP54BACHL", "NPT4_PUB", "NPT41_PUB", "NPT42_PUB", "NPT43_PUB", "NPT44_PUB", "NPT45_PUB", "NPT4_048_PUB", "NPT4_3075_PUB", "NPT4_75UP_PUB", "NUM4_PUB", "NUM41_PUB", "NUM42_PUB", "NUM43_PUB", "NUM44_PUB", "NUM45_PUB", "PCTPELL", "C150_4", "D150_4", "C150_4_NRA", "PCTFLOAN", "COMPL_RPY_1YR_RT", "FEMALE_RPY_1YR_RT", "MALE_RPY_1YR_RT", "COMPL_RPY_3YR_RT", "FEMALE_RPY_3YR_RT", "MALE_RPY_3YR_RT", "COMPL_RPY_5YR_RT", "FEMALE_RPY_5YR_RT", "MALE_RPY_5YR_RT", "GRAD_DEBT_MDN", "WDRAW_DEBT_MDN", "LO_INC_DEBT_MDN", "MD_INC_DEBT_MDN", "HI_INC_DEBT_MDN", "DEP_DEBT_MDN", "IND_DEBT_MDN", "PELL_DEBT_MDN", "NOPELL_DEBT_MDN", "FEMALE_DEBT_MDN", "MALE_DEBT_MDN", "FIRSTGEN_DEBT_MDN", "NOTFIRSTGEN_DEBT_MDN", "DEBT_N", "GRAD_DEBT_N", "WDRAW_DEBT_N", "LO_INC_DEBT_N", "MD_INC_DEBT_N", "HI_INC_DEBT_N", "DEP_DEBT_N", "IND_DEBT_N", "PELL_DEBT_N", "NOPELL_DEBT_N", "FEMALE_DEBT_N", "MALE_DEBT_N", "FIRSTGEN_DEBT_N", "NOTFIRSTGEN_DEBT_N", "FEMALE_RPY_1YR_N", "MALE_RPY_1YR_N", "FEMALE_RPY_3YR_N", "MALE_RPY_3YR_N", "FEMALE_RPY_5YR_N", "MALE_RPY_5YR_N", "MN_EARN_WNE_INDEP0_P6", "MN_EARN_WNE_INDEP1_P6", "MN_EARN_WNE_MALE0_P6", "MN_EARN_WNE_MALE1_P6", "GRAD_DEBT_MDN_SUPP", "FEMALE_RPY_3YR_RT_SUPP", "MALE_RPY_3YR_RT_SUPP", "C100_4", "D150_4_WHITE", "D150_4_BLACK", "D150_4_HISP", "D150_4_ASIAN", "D150_4_AIAN", "D150_4_NHPI", "D150_4_2MOR", "D150_4_NRA", "D150_4_UNKN", "Year")]
```

```{r message=FALSE, cache=FALSE, echo=FALSE, warning=FALSE}
MERGED2015_16_PP <- read_excel("MERGED2015_16_PP.xlsx")
MERGED2015_16_PP <- merge(bigten, MERGED2015_16_PP, by.x="UNITID", by.y="UNITID", all.x = TRUE)
MERGED2015_16_PP$Year <- "2015-16"

MERGED2015_16_PP <- MERGED2015_16_PP[,c("PCIP01", "PCIP03", "PCIP04", "PCIP05", "PCIP09", "PCIP10", "PCIP11", "PCIP12", "PCIP13", "PCIP14", "PCIP15", "PCIP16", "PCIP19", "PCIP22", "PCIP23", "PCIP24", "PCIP25", "PCIP26", "PCIP27", "PCIP29", "PCIP30", "PCIP31", "PCIP38", "PCIP39", "PCIP40", "PCIP41", "PCIP42", "PCIP43", "PCIP44", "PCIP45", "PCIP46", "PCIP47", "PCIP48", "PCIP49", "PCIP50", "PCIP51", "PCIP52", "PCIP54", "CIP01BACHL", "CIP03BACHL", "CIP04BACHL", "CIP05BACHL", "CIP09BACHL", "CIP10BACHL", "CIP11BACHL", "CIP12BACHL", "CIP13BACHL", "CIP14BACHL", "CIP15BACHL", "CIP16BACHL", "CIP19BACHL", "CIP22BACHL", "CIP23BACHL", "CIP24BACHL", "CIP25BACHL", "CIP26BACHL", "CIP27BACHL", "CIP29BACHL", "CIP30BACHL", "CIP31BACHL", "CIP38BACHL", "CIP39BACHL", "CIP40BACHL", "CIP41BACHL", "CIP42BACHL", "CIP43BACHL", "CIP44BACHL", "CIP45BACHL", "CIP46BACHL", "CIP47BACHL", "CIP48BACHL", "CIP49BACHL", "CIP50BACHL", "CIP51BACHL", "CIP52BACHL", "CIP54BACHL", "NPT4_PUB", "NPT41_PUB", "NPT42_PUB", "NPT43_PUB", "NPT44_PUB", "NPT45_PUB", "NPT4_048_PUB", "NPT4_3075_PUB", "NPT4_75UP_PUB", "NUM4_PUB", "NUM41_PUB", "NUM42_PUB", "NUM43_PUB", "NUM44_PUB", "NUM45_PUB", "PCTPELL", "C150_4", "D150_4", "C150_4_NRA", "PCTFLOAN", "COMPL_RPY_1YR_RT", "FEMALE_RPY_1YR_RT", "MALE_RPY_1YR_RT", "COMPL_RPY_3YR_RT", "FEMALE_RPY_3YR_RT", "MALE_RPY_3YR_RT", "COMPL_RPY_5YR_RT", "FEMALE_RPY_5YR_RT", "MALE_RPY_5YR_RT", "GRAD_DEBT_MDN", "WDRAW_DEBT_MDN", "LO_INC_DEBT_MDN", "MD_INC_DEBT_MDN", "HI_INC_DEBT_MDN", "DEP_DEBT_MDN", "IND_DEBT_MDN", "PELL_DEBT_MDN", "NOPELL_DEBT_MDN", "FEMALE_DEBT_MDN", "MALE_DEBT_MDN", "FIRSTGEN_DEBT_MDN", "NOTFIRSTGEN_DEBT_MDN", "DEBT_N", "GRAD_DEBT_N", "WDRAW_DEBT_N", "LO_INC_DEBT_N", "MD_INC_DEBT_N", "HI_INC_DEBT_N", "DEP_DEBT_N", "IND_DEBT_N", "PELL_DEBT_N", "NOPELL_DEBT_N", "FEMALE_DEBT_N", "MALE_DEBT_N", "FIRSTGEN_DEBT_N", "NOTFIRSTGEN_DEBT_N", "FEMALE_RPY_1YR_N", "MALE_RPY_1YR_N", "FEMALE_RPY_3YR_N", "MALE_RPY_3YR_N", "FEMALE_RPY_5YR_N", "MALE_RPY_5YR_N", "MN_EARN_WNE_INDEP0_P6", "MN_EARN_WNE_INDEP1_P6", "MN_EARN_WNE_MALE0_P6", "MN_EARN_WNE_MALE1_P6", "GRAD_DEBT_MDN_SUPP", "FEMALE_RPY_3YR_RT_SUPP", "MALE_RPY_3YR_RT_SUPP", "C100_4", "D150_4_WHITE", "D150_4_BLACK", "D150_4_HISP", "D150_4_ASIAN", "D150_4_AIAN", "D150_4_NHPI", "D150_4_2MOR", "D150_4_NRA", "D150_4_UNKN", "Year")]
```

```{r message=FALSE, cache=FALSE, echo=FALSE, warning=FALSE}
MERGED2014_15_PP <- read_excel("MERGED2014_15_PP.xlsx")
MERGED2014_15_PP <- merge(bigten, MERGED2014_15_PP, by.x="UNITID", by.y="UNITID", all.x = TRUE)
MERGED2014_15_PP$Year <- "2014-15"

MERGED2014_15_PP <- MERGED2014_15_PP[,c("PCIP01", "PCIP03", "PCIP04", "PCIP05", "PCIP09", "PCIP10", "PCIP11", "PCIP12", "PCIP13", "PCIP14", "PCIP15", "PCIP16", "PCIP19", "PCIP22", "PCIP23", "PCIP24", "PCIP25", "PCIP26", "PCIP27", "PCIP29", "PCIP30", "PCIP31", "PCIP38", "PCIP39", "PCIP40", "PCIP41", "PCIP42", "PCIP43", "PCIP44", "PCIP45", "PCIP46", "PCIP47", "PCIP48", "PCIP49", "PCIP50", "PCIP51", "PCIP52", "PCIP54", "CIP01BACHL", "CIP03BACHL", "CIP04BACHL", "CIP05BACHL", "CIP09BACHL", "CIP10BACHL", "CIP11BACHL", "CIP12BACHL", "CIP13BACHL", "CIP14BACHL", "CIP15BACHL", "CIP16BACHL", "CIP19BACHL", "CIP22BACHL", "CIP23BACHL", "CIP24BACHL", "CIP25BACHL", "CIP26BACHL", "CIP27BACHL", "CIP29BACHL", "CIP30BACHL", "CIP31BACHL", "CIP38BACHL", "CIP39BACHL", "CIP40BACHL", "CIP41BACHL", "CIP42BACHL", "CIP43BACHL", "CIP44BACHL", "CIP45BACHL", "CIP46BACHL", "CIP47BACHL", "CIP48BACHL", "CIP49BACHL", "CIP50BACHL", "CIP51BACHL", "CIP52BACHL", "CIP54BACHL", "NPT4_PUB", "NPT41_PUB", "NPT42_PUB", "NPT43_PUB", "NPT44_PUB", "NPT45_PUB", "NPT4_048_PUB", "NPT4_3075_PUB", "NPT4_75UP_PUB", "NUM4_PUB", "NUM41_PUB", "NUM42_PUB", "NUM43_PUB", "NUM44_PUB", "NUM45_PUB", "PCTPELL", "C150_4", "D150_4", "C150_4_NRA", "PCTFLOAN", "COMPL_RPY_1YR_RT", "FEMALE_RPY_1YR_RT", "MALE_RPY_1YR_RT", "COMPL_RPY_3YR_RT", "FEMALE_RPY_3YR_RT", "MALE_RPY_3YR_RT", "COMPL_RPY_5YR_RT", "FEMALE_RPY_5YR_RT", "MALE_RPY_5YR_RT", "GRAD_DEBT_MDN", "WDRAW_DEBT_MDN", "LO_INC_DEBT_MDN", "MD_INC_DEBT_MDN", "HI_INC_DEBT_MDN", "DEP_DEBT_MDN", "IND_DEBT_MDN", "PELL_DEBT_MDN", "NOPELL_DEBT_MDN", "FEMALE_DEBT_MDN", "MALE_DEBT_MDN", "FIRSTGEN_DEBT_MDN", "NOTFIRSTGEN_DEBT_MDN", "DEBT_N", "GRAD_DEBT_N", "WDRAW_DEBT_N", "LO_INC_DEBT_N", "MD_INC_DEBT_N", "HI_INC_DEBT_N", "DEP_DEBT_N", "IND_DEBT_N", "PELL_DEBT_N", "NOPELL_DEBT_N", "FEMALE_DEBT_N", "MALE_DEBT_N", "FIRSTGEN_DEBT_N", "NOTFIRSTGEN_DEBT_N", "FEMALE_RPY_1YR_N", "MALE_RPY_1YR_N", "FEMALE_RPY_3YR_N", "MALE_RPY_3YR_N", "FEMALE_RPY_5YR_N", "MALE_RPY_5YR_N", "MN_EARN_WNE_INDEP0_P6", "MN_EARN_WNE_INDEP1_P6", "MN_EARN_WNE_MALE0_P6", "MN_EARN_WNE_MALE1_P6", "GRAD_DEBT_MDN_SUPP", "FEMALE_RPY_3YR_RT_SUPP", "MALE_RPY_3YR_RT_SUPP", "C100_4", "D150_4_WHITE", "D150_4_BLACK", "D150_4_HISP", "D150_4_ASIAN", "D150_4_AIAN", "D150_4_NHPI", "D150_4_2MOR", "D150_4_NRA", "D150_4_UNKN", "Year")]
```

```{r message=FALSE, cache=FALSE, echo=FALSE, warning=FALSE}
MERGED2013_14_PP <- read_excel("MERGED2013_14_PP.xlsx")
MERGED2013_14_PP <- merge(bigten, MERGED2013_14_PP, by.x="UNITID", by.y="UNITID", all.x = TRUE)
MERGED2013_14_PP$Year <- "2013-14"

MERGED2013_14_PP <- MERGED2013_14_PP[,c("PCIP01", "PCIP03", "PCIP04", "PCIP05", "PCIP09", "PCIP10", "PCIP11", "PCIP12", "PCIP13", "PCIP14", "PCIP15", "PCIP16", "PCIP19", "PCIP22", "PCIP23", "PCIP24", "PCIP25", "PCIP26", "PCIP27", "PCIP29", "PCIP30", "PCIP31", "PCIP38", "PCIP39", "PCIP40", "PCIP41", "PCIP42", "PCIP43", "PCIP44", "PCIP45", "PCIP46", "PCIP47", "PCIP48", "PCIP49", "PCIP50", "PCIP51", "PCIP52", "PCIP54", "CIP01BACHL", "CIP03BACHL", "CIP04BACHL", "CIP05BACHL", "CIP09BACHL", "CIP10BACHL", "CIP11BACHL", "CIP12BACHL", "CIP13BACHL", "CIP14BACHL", "CIP15BACHL", "CIP16BACHL", "CIP19BACHL", "CIP22BACHL", "CIP23BACHL", "CIP24BACHL", "CIP25BACHL", "CIP26BACHL", "CIP27BACHL", "CIP29BACHL", "CIP30BACHL", "CIP31BACHL", "CIP38BACHL", "CIP39BACHL", "CIP40BACHL", "CIP41BACHL", "CIP42BACHL", "CIP43BACHL", "CIP44BACHL", "CIP45BACHL", "CIP46BACHL", "CIP47BACHL", "CIP48BACHL", "CIP49BACHL", "CIP50BACHL", "CIP51BACHL", "CIP52BACHL", "CIP54BACHL", "NPT4_PUB", "NPT41_PUB", "NPT42_PUB", "NPT43_PUB", "NPT44_PUB", "NPT45_PUB", "NPT4_048_PUB", "NPT4_3075_PUB", "NPT4_75UP_PUB", "NUM4_PUB", "NUM41_PUB", "NUM42_PUB", "NUM43_PUB", "NUM44_PUB", "NUM45_PUB", "PCTPELL", "C150_4", "D150_4", "C150_4_NRA", "PCTFLOAN", "COMPL_RPY_1YR_RT", "FEMALE_RPY_1YR_RT", "MALE_RPY_1YR_RT", "COMPL_RPY_3YR_RT", "FEMALE_RPY_3YR_RT", "MALE_RPY_3YR_RT", "COMPL_RPY_5YR_RT", "FEMALE_RPY_5YR_RT", "MALE_RPY_5YR_RT", "GRAD_DEBT_MDN", "WDRAW_DEBT_MDN", "LO_INC_DEBT_MDN", "MD_INC_DEBT_MDN", "HI_INC_DEBT_MDN", "DEP_DEBT_MDN", "IND_DEBT_MDN", "PELL_DEBT_MDN", "NOPELL_DEBT_MDN", "FEMALE_DEBT_MDN", "MALE_DEBT_MDN", "FIRSTGEN_DEBT_MDN", "NOTFIRSTGEN_DEBT_MDN", "DEBT_N", "GRAD_DEBT_N", "WDRAW_DEBT_N", "LO_INC_DEBT_N", "MD_INC_DEBT_N", "HI_INC_DEBT_N", "DEP_DEBT_N", "IND_DEBT_N", "PELL_DEBT_N", "NOPELL_DEBT_N", "FEMALE_DEBT_N", "MALE_DEBT_N", "FIRSTGEN_DEBT_N", "NOTFIRSTGEN_DEBT_N", "FEMALE_RPY_1YR_N", "MALE_RPY_1YR_N", "FEMALE_RPY_3YR_N", "MALE_RPY_3YR_N", "FEMALE_RPY_5YR_N", "MALE_RPY_5YR_N", "MN_EARN_WNE_INDEP0_P6", "MN_EARN_WNE_INDEP1_P6", "MN_EARN_WNE_MALE0_P6", "MN_EARN_WNE_MALE1_P6", "GRAD_DEBT_MDN_SUPP", "FEMALE_RPY_3YR_RT_SUPP", "MALE_RPY_3YR_RT_SUPP", "C100_4", "D150_4_WHITE", "D150_4_BLACK", "D150_4_HISP", "D150_4_ASIAN", "D150_4_AIAN", "D150_4_NHPI", "D150_4_2MOR", "D150_4_NRA", "D150_4_UNKN", "Year")]
```

```{r message=FALSE, cache=FALSE, echo=FALSE, warning=FALSE}
MERGED2012_13_PP <- read_excel("MERGED2012_13_PP.xlsx")
MERGED2012_13_PP <- merge(bigten, MERGED2012_13_PP, by.x="UNITID", by.y="UNITID", all.x = TRUE)
MERGED2012_13_PP$Year <- "2012-13"

MERGED2012_13_PP <- MERGED2012_13_PP[,c("PCIP01", "PCIP03", "PCIP04", "PCIP05", "PCIP09", "PCIP10", "PCIP11", "PCIP12", "PCIP13", "PCIP14", "PCIP15", "PCIP16", "PCIP19", "PCIP22", "PCIP23", "PCIP24", "PCIP25", "PCIP26", "PCIP27", "PCIP29", "PCIP30", "PCIP31", "PCIP38", "PCIP39", "PCIP40", "PCIP41", "PCIP42", "PCIP43", "PCIP44", "PCIP45", "PCIP46", "PCIP47", "PCIP48", "PCIP49", "PCIP50", "PCIP51", "PCIP52", "PCIP54", "CIP01BACHL", "CIP03BACHL", "CIP04BACHL", "CIP05BACHL", "CIP09BACHL", "CIP10BACHL", "CIP11BACHL", "CIP12BACHL", "CIP13BACHL", "CIP14BACHL", "CIP15BACHL", "CIP16BACHL", "CIP19BACHL", "CIP22BACHL", "CIP23BACHL", "CIP24BACHL", "CIP25BACHL", "CIP26BACHL", "CIP27BACHL", "CIP29BACHL", "CIP30BACHL", "CIP31BACHL", "CIP38BACHL", "CIP39BACHL", "CIP40BACHL", "CIP41BACHL", "CIP42BACHL", "CIP43BACHL", "CIP44BACHL", "CIP45BACHL", "CIP46BACHL", "CIP47BACHL", "CIP48BACHL", "CIP49BACHL", "CIP50BACHL", "CIP51BACHL", "CIP52BACHL", "CIP54BACHL", "NPT4_PUB", "NPT41_PUB", "NPT42_PUB", "NPT43_PUB", "NPT44_PUB", "NPT45_PUB", "NPT4_048_PUB", "NPT4_3075_PUB", "NPT4_75UP_PUB", "NUM4_PUB", "NUM41_PUB", "NUM42_PUB", "NUM43_PUB", "NUM44_PUB", "NUM45_PUB", "PCTPELL", "C150_4", "D150_4", "C150_4_NRA", "PCTFLOAN", "COMPL_RPY_1YR_RT", "FEMALE_RPY_1YR_RT", "MALE_RPY_1YR_RT", "COMPL_RPY_3YR_RT", "FEMALE_RPY_3YR_RT", "MALE_RPY_3YR_RT", "COMPL_RPY_5YR_RT", "FEMALE_RPY_5YR_RT", "MALE_RPY_5YR_RT", "GRAD_DEBT_MDN", "WDRAW_DEBT_MDN", "LO_INC_DEBT_MDN", "MD_INC_DEBT_MDN", "HI_INC_DEBT_MDN", "DEP_DEBT_MDN", "IND_DEBT_MDN", "PELL_DEBT_MDN", "NOPELL_DEBT_MDN", "FEMALE_DEBT_MDN", "MALE_DEBT_MDN", "FIRSTGEN_DEBT_MDN", "NOTFIRSTGEN_DEBT_MDN", "DEBT_N", "GRAD_DEBT_N", "WDRAW_DEBT_N", "LO_INC_DEBT_N", "MD_INC_DEBT_N", "HI_INC_DEBT_N", "DEP_DEBT_N", "IND_DEBT_N", "PELL_DEBT_N", "NOPELL_DEBT_N", "FEMALE_DEBT_N", "MALE_DEBT_N", "FIRSTGEN_DEBT_N", "NOTFIRSTGEN_DEBT_N", "FEMALE_RPY_1YR_N", "MALE_RPY_1YR_N", "FEMALE_RPY_3YR_N", "MALE_RPY_3YR_N", "FEMALE_RPY_5YR_N", "MALE_RPY_5YR_N", "MN_EARN_WNE_INDEP0_P6", "MN_EARN_WNE_INDEP1_P6", "MN_EARN_WNE_MALE0_P6", "MN_EARN_WNE_MALE1_P6", "GRAD_DEBT_MDN_SUPP", "FEMALE_RPY_3YR_RT_SUPP", "MALE_RPY_3YR_RT_SUPP", "C100_4", "D150_4_WHITE", "D150_4_BLACK", "D150_4_HISP", "D150_4_ASIAN", "D150_4_AIAN", "D150_4_NHPI", "D150_4_2MOR", "D150_4_NRA", "D150_4_UNKN", "Year")]
```

```{r message=FALSE, cache=FALSE, echo=FALSE, warning=FALSE}
combined <- rbind(MERGED2016_17_PP, MERGED2015_16_PP, MERGED2014_15_PP, MERGED2013_14_PP, MERGED2012_13_PP)

 # Removes the individual years
rm(MERGED2016_17_PP, MERGED2015_16_PP, MERGED2014_15_PP, MERGED2013_14_PP, MERGED2012_13_PP)
# Counts the number of "n/a" exist in each column of the final data frame, IPEDS
combined_na_count <- sapply(combined, function(x) sum(is.na(x)))
combined_na_count <- as.data.frame.list(combined_na_count)
# Moves the data from wide to long:
library(reshape2)
combined_na_count <- melt(combined_na_count)
 # Writes a text file to working directory 
 write.table(combined,"combined_college_scorecards.txt",sep="\t",row.names=FALSE)
```
